Sprint 0001
neosoma/ventas-udemy-course pull request #1
Opened 2021-03-04 21:27 UTC by franciscoguemes

Cambios anadidos

- README.md
- API_Calls.md
- Manejador de errores para URLs sin mapear
- Ejemplo de código sin lambdas

2021-03-05 00:15 UTC, neosoma commented on API_Calls.md
> +curl http://localhost:9090/api/clientes/ | jq .[0]
Una vez instalado el cURL, no reconoce los comandos (json_pp, jp) en Windows.
¿Alguna sugerencia?

2021-03-05 00:23 UTC, neosoma requested changes

2021-03-05 00:23 UTC, neosoma commented on API_Calls.md
> +curl http://localhost:9090/api/clientes/ | jq .[0]
Una vez instalado el cURL, no reconoce los comandos (json_pp, jp) en Windows.
¿Alguna sugerencia?

2021-03-05 16:50 UTC, franciscoguemes commented on API_Calls.md
> +curl http://localhost:9090/api/clientes/ | jq .[0]
Eso es que no tienes instalado json_pp ni jq. No son comandos que vengan por defecto con el SO, ni siquiera en Linux. Puedes instalarlos desde sus páginas oficiales:

- JQ -->  https://stedolan.github.io/jq/
- JSON_PP --> https://metacpan.org/release/JSON-PP

El maś útil es jq, puesto que hace las dos funciones, te pone el JSON bonito y además puedes hacer consultas.

2021-03-06 01:16 UTC, merged

2021-03-06 01:20 UTC, neosoma commented
Ya he hecho un Merge de la rama de Sprint con la de Master (que también he
configurado para que esté por defecto.
GitHub me indicaba que la rama Sprint se podía borrar de forma segura, pero
no la he eliminado porque no sé cómo se suele proceder habitualmente: Si
quieres mantener esta rama para ir añadiendo nuevas modificaciones, o si lo
propio es borrarla y cuando hagas modificaciones generes otra nueva.

Lo que tú me vayas indicando.
¡Buena aportación, gracias!

---
Óscar Hernández Santos
*Tfno:* 688 90 88 01
*Dirección: *Avda. Cantabria 41, oficina 6, Burgos
*www.espaciodavinci.es <http://www.espaciodavinci.es>*


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

El jue, 4 mar 2021 a las 22:27, Francisco Güemes (<notifications@github.com>)
escribió:

> Cambios anadidos
>
>    - README.md
>    - API_Calls.md
>    - Manejador de errores para URLs sin mapear
>    - Ejemplo de código sin lambdas
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/neosoma/ventas-udemy-course/pull/1
> Commit Summary
>
>    - Add README.md file.
>    - Add an ErrorHandler to avoid Whitelabel error pages.
>    - Add API calls examples.
>    - Add an example of Java Vanilla code that does the same as lambdas.
>
> File Changes
>
>    - *A* API_Calls.md
>    <https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-aba3c5b82dfdbeb1f04c965e4778df56d55dba5db572d34ecceb6e2a32768c6b>
>    (53)
>    - *A* README.md
>    <https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5>
>    (76)
>    - *M* src/main/java/com/ventas/ventas/controller/ClienteController.java
>    <https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-79b3cfaa310dda5366c476edd84e4557abc3cecfe24981936fe7372ac84b7f78>
>    (13)
>    - *A*
>    src/main/java/com/ventas/ventas/controller/ErrorHandlerController.java
>    <https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-2ec20e5934d4d0949a45797b8794b9063b2983a783095c55d74d5bf0537de94b>
>    (24)
>
> Patch Links:
>
>    - https://github.com/neosoma/ventas-udemy-course/pull/1.patch
>    - https://github.com/neosoma/ventas-udemy-course/pull/1.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neosoma/ventas-udemy-course/pull/1>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDW7H654C5W4KMMX2KBQZDTB73NVANCNFSM4YUAPMDA>
> .
>

2021-03-06 08:35 UTC, franciscoguemes commented
Hola,

Normalmente una vez se ha mergeado la rama secundaria (en este caso
sprint-0001) en la rama principal ( bien sea main, master o cualquier otra)
se debe generar una nueva rama para hacer cambios, especialmente si los
nuevos cambios no están relacionados, por ejemplo el desarrollo de una
nueva funcionalidad.

Si por ejemplo una vez se ha mergeado sprint-0001 en la rama principal, se
detectara un bug (derivado del nuevo incremento de código), ahí ya es más
filosófico, hay gente que reusa la misma rama y hay gente que genera una
nueva. Todo depende de cómo tengan definido el proceso de scrum en este
caso. Generalmente las ramas van asociadas a tickets que son gestionados
por herramientas de gestión de tareas ( Jira, gitlab, etc...).

En nuestro caso lo que podemos hacer es no borrar las ramas, pero para
nuevas funcionalidades se deben crear ramas nuevas.

Si quieres os puedo contar otro día más sobre el proceso de Scrum y las
herramientas de gestión de tareas y cómo se integra todo esto con el
control de versiones. Aunque no sé si los chavales van a estar interesados
en este tema en particular xD.

Saludos,

Francisco

P.D. Has tenido la mala suerte de que he visto tu mail en un tren y no
tengo nada mejor que hacer, así que te ha tocado la explicación chapa xD.



El sáb., 6 mar. 2021 2:20, neosoma <notifications@github.com> escribió:

> Ya he hecho un Merge de la rama de Sprint con la de Master (que también he
> configurado para que esté por defecto.
> GitHub me indicaba que la rama Sprint se podía borrar de forma segura, pero
> no la he eliminado porque no sé cómo se suele proceder habitualmente: Si
> quieres mantener esta rama para ir añadiendo nuevas modificaciones, o si lo
> propio es borrarla y cuando hagas modificaciones generes otra nueva.
>
> Lo que tú me vayas indicando.
> ¡Buena aportación, gracias!
>
> ---
> Óscar Hernández Santos
> *Tfno:* 688 90 88 01
> *Dirección: *Avda. Cantabria 41, oficina 6, Burgos
> *www.espaciodavinci.es <http://www.espaciodavinci.es>*
>
>
> <
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> >
> Libre
> de virus. www.avast.com
> <
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> >
> <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>
> El jue, 4 mar 2021 a las 22:27, Francisco Güemes (<
> notifications@github.com>)
> escribió:
>
> > Cambios anadidos
> >
> > - README.md
> > - API_Calls.md
> > - Manejador de errores para URLs sin mapear
> > - Ejemplo de código sin lambdas
> >
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/neosoma/ventas-udemy-course/pull/1
> > Commit Summary
> >
> > - Add README.md file.
> > - Add an ErrorHandler to avoid Whitelabel error pages.
> > - Add API calls examples.
> > - Add an example of Java Vanilla code that does the same as lambdas.
> >
> > File Changes
> >
> > - *A* API_Calls.md
> > <
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-aba3c5b82dfdbeb1f04c965e4778df56d55dba5db572d34ecceb6e2a32768c6b
> >
> > (53)
> > - *A* README.md
> > <
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> >
> > (76)
> > - *M* src/main/java/com/ventas/ventas/controller/ClienteController.java
> > <
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-79b3cfaa310dda5366c476edd84e4557abc3cecfe24981936fe7372ac84b7f78
> >
> > (13)
> > - *A*
> > src/main/java/com/ventas/ventas/controller/ErrorHandlerController.java
> > <
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-2ec20e5934d4d0949a45797b8794b9063b2983a783095c55d74d5bf0537de94b
> >
> > (24)
> >
> > Patch Links:
> >
> > - https://github.com/neosoma/ventas-udemy-course/pull/1.patch
> > - https://github.com/neosoma/ventas-udemy-course/pull/1.diff
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/neosoma/ventas-udemy-course/pull/1>, or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ABDW7H654C5W4KMMX2KBQZDTB73NVANCNFSM4YUAPMDA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neosoma/ventas-udemy-course/pull/1#issuecomment-791826494>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIUHH56YU34BHUQ7NFNGZ3TTCF7NDANCNFSM4YUAPMDA>
> .
>

2021-03-06 10:07 UTC, neosoma commented
Esto es una chulada. Estoy hablando contigo y ni siquiera sé cómo funciona
este sistema de e-mails, jeje.

Genial, entonces podemos crear otra nueva branch, sin borrar la anterior
como comentas. Igual sería interesante mantener una con el código base del
curso. Ayer comprimí el proyecto y lo tengo en el ordenador aparte.

No sé si igual tiene más sentido tener sencillamente otro repositorio
distinto para ello, o una rama tiene más sentido si no emborrona el flujo
del desarrollo.

Ayer miré para hacer una rama nueva pero no encontré en GitHub ningún
generate new branch. Aparte, imagino que habrá que configurarlo en eclipse
para mantener distintos repositorios.

Me baje GitHub Desktop también para ver cómo va.

He creado una tabla Pedido con sus clases asociadas y su controller, y
parece que me funcionó. Cuando sepa dónde subirlo lo subo postre que le
saques fallos con palomitas. No sé cuál sería el mejor lugar en GitHub para
dejar ejemplo de requests de ejemplo.

Lo de ver el tema de scrum con ellos es una gran idea. Creo que les
gustará. Les podemos ir incorporando poco a poco a algún proyecto para que
empiecen a practicar el flujo real.

Aparte, también conseguí ejecutar jq después de un rato de cacharreo. Creo
que postman les hará la vida más fácil al principio, pero creo que está
bien que vayan conociendo herramientas, así que les dejaré cómo lo instalé
en Windows y tú doc está perfecta en GitHub.

Esto sí que habrá sido entretenimiento para un tren! 😜

Feliz finde y gracias de nuevo por tus conocimientos. Los iré reflejando en
la doc del curso

El sáb., 6 mar. 2021 9:35, Francisco Güemes <notifications@github.com>
escribió:

> Hola,
>
> Normalmente una vez se ha mergeado la rama secundaria (en este caso
> sprint-0001) en la rama principal ( bien sea main, master o cualquier otra)
> se debe generar una nueva rama para hacer cambios, especialmente si los
> nuevos cambios no están relacionados, por ejemplo el desarrollo de una
> nueva funcionalidad.
>
> Si por ejemplo una vez se ha mergeado sprint-0001 en la rama principal, se
> detectara un bug (derivado del nuevo incremento de código), ahí ya es más
> filosófico, hay gente que reusa la misma rama y hay gente que genera una
> nueva. Todo depende de cómo tengan definido el proceso de scrum en este
> caso. Generalmente las ramas van asociadas a tickets que son gestionados
> por herramientas de gestión de tareas ( Jira, gitlab, etc...).
>
> En nuestro caso lo que podemos hacer es no borrar las ramas, pero para
> nuevas funcionalidades se deben crear ramas nuevas.
>
> Si quieres os puedo contar otro día más sobre el proceso de Scrum y las
> herramientas de gestión de tareas y cómo se integra todo esto con el
> control de versiones. Aunque no sé si los chavales van a estar interesados
> en este tema en particular xD.
>
> Saludos,
>
> Francisco
>
> P.D. Has tenido la mala suerte de que he visto tu mail en un tren y no
> tengo nada mejor que hacer, así que te ha tocado la explicación chapa xD.
>
>
>
> El sáb., 6 mar. 2021 2:20, neosoma <notifications@github.com> escribió:
>
> > Ya he hecho un Merge de la rama de Sprint con la de Master (que también
> he
> > configurado para que esté por defecto.
> > GitHub me indicaba que la rama Sprint se podía borrar de forma segura,
> pero
> > no la he eliminado porque no sé cómo se suele proceder habitualmente: Si
> > quieres mantener esta rama para ir añadiendo nuevas modificaciones, o si
> lo
> > propio es borrarla y cuando hagas modificaciones generes otra nueva.
> >
> > Lo que tú me vayas indicando.
> > ¡Buena aportación, gracias!
> >
> > ---
> > Óscar Hernández Santos
> > *Tfno:* 688 90 88 01
> > *Dirección: *Avda. Cantabria 41, oficina 6, Burgos
> > *www.espaciodavinci.es <http://www.espaciodavinci.es>*
> >
> >
> > <
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> > >
> > Libre
> > de virus. www.avast.com
> > <
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> > >
> > <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
> >
> > El jue, 4 mar 2021 a las 22:27, Francisco Güemes (<
> > notifications@github.com>)
> > escribió:
> >
> > > Cambios anadidos
> > >
> > > - README.md
> > > - API_Calls.md
> > > - Manejador de errores para URLs sin mapear
> > > - Ejemplo de código sin lambdas
> > >
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/neosoma/ventas-udemy-course/pull/1
> > > Commit Summary
> > >
> > > - Add README.md file.
> > > - Add an ErrorHandler to avoid Whitelabel error pages.
> > > - Add API calls examples.
> > > - Add an example of Java Vanilla code that does the same as lambdas.
> > >
> > > File Changes
> > >
> > > - *A* API_Calls.md
> > > <
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-aba3c5b82dfdbeb1f04c965e4778df56d55dba5db572d34ecceb6e2a32768c6b
> > >
> > > (53)
> > > - *A* README.md
> > > <
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> > >
> > > (76)
> > > - *M* src/main/java/com/ventas/ventas/controller/ClienteController.java
> > > <
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-79b3cfaa310dda5366c476edd84e4557abc3cecfe24981936fe7372ac84b7f78
> > >
> > > (13)
> > > - *A*
> > > src/main/java/com/ventas/ventas/controller/ErrorHandlerController.java
> > > <
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-2ec20e5934d4d0949a45797b8794b9063b2983a783095c55d74d5bf0537de94b
> > >
> > > (24)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/neosoma/ventas-udemy-course/pull/1.patch
> > > - https://github.com/neosoma/ventas-udemy-course/pull/1.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/neosoma/ventas-udemy-course/pull/1>, or
> unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/ABDW7H654C5W4KMMX2KBQZDTB73NVANCNFSM4YUAPMDA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/neosoma/ventas-udemy-course/pull/1#issuecomment-791826494
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AIUHH56YU34BHUQ7NFNGZ3TTCF7NDANCNFSM4YUAPMDA
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/neosoma/ventas-udemy-course/pull/1#issuecomment-791896199>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDW7H4FNLBIPOLMBICUDULTCHSMDANCNFSM4YUAPMDA>
> .
>

2021-03-06 18:26 UTC, franciscoguemes commented
Hola Oscar,

Básicamente el sistema de E-Mails va asociado a los comentarios de la Pull
Request (o Merge Request en gitlab) en GitHub xD.

 Puedes crear las ramas que quieras, ese es el concepto de git! Por eso se
llama control de versiones descentralizado.

El código del curso se lo pueden bajar del curso directamente o bien pueden
hacer un rebase de Master al commit inicial ( así los fuerzas a usar
funcionalidad avanzada de git ).

Si mal no recuerdo, en GitHub tienes un botón para crear ramas. De todas
formas lo mejor es usar git directamente desde el terminal, aunque yo lo
uso mucho desde Eclipse, es muy cómodo puesto que está bastante bien
integrado.

No te puedo decir nada del GitHub Desktop porque no lo he usado nunca, lo
único que te puedo decir es que todos los GUI que he probado ( Source tree,
gitkraken, etc ... ) me han dado algún problema y los he acabado desechando
por el terminal de Linux para cosas serias y la integración de Eclipse para
el día a día.

Crea una rama y sube lo que has creado y lo hecho un ojo a ver. Las
requests de ejemplo en el API_calls.md o sino crea otro fichero *.md y
explicas ahí la request y el Json que mandas.

Para empezar que usen Postman, que con la interfaz gráfica parece más
amigable. Yo simplemente añadí lo del curl por dar opciones y porque pasaba
de instalarme el Postman xD.

Pues ahora estoy otra vez en el tren volviendo a casa después de pasar el
día en la montaña.

Buen finde!

Francisco



El sáb., 6 mar. 2021 11:07, neosoma <notifications@github.com> escribió:

> Esto es una chulada. Estoy hablando contigo y ni siquiera sé cómo funciona
> este sistema de e-mails, jeje.
>
> Genial, entonces podemos crear otra nueva branch, sin borrar la anterior
> como comentas. Igual sería interesante mantener una con el código base del
> curso. Ayer comprimí el proyecto y lo tengo en el ordenador aparte.
>
> No sé si igual tiene más sentido tener sencillamente otro repositorio
> distinto para ello, o una rama tiene más sentido si no emborrona el flujo
> del desarrollo.
>
> Ayer miré para hacer una rama nueva pero no encontré en GitHub ningún
> generate new branch. Aparte, imagino que habrá que configurarlo en eclipse
> para mantener distintos repositorios.
>
> Me baje GitHub Desktop también para ver cómo va.
>
> He creado una tabla Pedido con sus clases asociadas y su controller, y
> parece que me funcionó. Cuando sepa dónde subirlo lo subo postre que le
> saques fallos con palomitas. No sé cuál sería el mejor lugar en GitHub para
> dejar ejemplo de requests de ejemplo.
>
> Lo de ver el tema de scrum con ellos es una gran idea. Creo que les
> gustará. Les podemos ir incorporando poco a poco a algún proyecto para que
> empiecen a practicar el flujo real.
>
> Aparte, también conseguí ejecutar jq después de un rato de cacharreo. Creo
> que postman les hará la vida más fácil al principio, pero creo que está
> bien que vayan conociendo herramientas, así que les dejaré cómo lo instalé
> en Windows y tú doc está perfecta en GitHub.
>
> Esto sí que habrá sido entretenimiento para un tren! 😜
>
> Feliz finde y gracias de nuevo por tus conocimientos. Los iré reflejando en
> la doc del curso
>
> El sáb., 6 mar. 2021 9:35, Francisco Güemes <notifications@github.com>
> escribió:
>
> > Hola,
> >
> > Normalmente una vez se ha mergeado la rama secundaria (en este caso
> > sprint-0001) en la rama principal ( bien sea main, master o cualquier
> otra)
> > se debe generar una nueva rama para hacer cambios, especialmente si los
> > nuevos cambios no están relacionados, por ejemplo el desarrollo de una
> > nueva funcionalidad.
> >
> > Si por ejemplo una vez se ha mergeado sprint-0001 en la rama principal,
> se
> > detectara un bug (derivado del nuevo incremento de código), ahí ya es más
> > filosófico, hay gente que reusa la misma rama y hay gente que genera una
> > nueva. Todo depende de cómo tengan definido el proceso de scrum en este
> > caso. Generalmente las ramas van asociadas a tickets que son gestionados
> > por herramientas de gestión de tareas ( Jira, gitlab, etc...).
> >
> > En nuestro caso lo que podemos hacer es no borrar las ramas, pero para
> > nuevas funcionalidades se deben crear ramas nuevas.
> >
> > Si quieres os puedo contar otro día más sobre el proceso de Scrum y las
> > herramientas de gestión de tareas y cómo se integra todo esto con el
> > control de versiones. Aunque no sé si los chavales van a estar
> interesados
> > en este tema en particular xD.
> >
> > Saludos,
> >
> > Francisco
> >
> > P.D. Has tenido la mala suerte de que he visto tu mail en un tren y no
> > tengo nada mejor que hacer, así que te ha tocado la explicación chapa xD.
> >
> >
> >
> > El sáb., 6 mar. 2021 2:20, neosoma <notifications@github.com> escribió:
> >
> > > Ya he hecho un Merge de la rama de Sprint con la de Master (que también
> > he
> > > configurado para que esté por defecto.
> > > GitHub me indicaba que la rama Sprint se podía borrar de forma segura,
> > pero
> > > no la he eliminado porque no sé cómo se suele proceder habitualmente:
> Si
> > > quieres mantener esta rama para ir añadiendo nuevas modificaciones, o
> si
> > lo
> > > propio es borrarla y cuando hagas modificaciones generes otra nueva.
> > >
> > > Lo que tú me vayas indicando.
> > > ¡Buena aportación, gracias!
> > >
> > > ---
> > > Óscar Hernández Santos
> > > *Tfno:* 688 90 88 01
> > > *Dirección: *Avda. Cantabria 41, oficina 6, Burgos
> > > *www.espaciodavinci.es <http://www.espaciodavinci.es>*
> > >
> > >
> > > <
> > >
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> > > >
> > > Libre
> > > de virus. www.avast.com
> > > <
> > >
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> > > >
> > > <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
> > >
> > > El jue, 4 mar 2021 a las 22:27, Francisco Güemes (<
> > > notifications@github.com>)
> > > escribió:
> > >
> > > > Cambios anadidos
> > > >
> > > > - README.md
> > > > - API_Calls.md
> > > > - Manejador de errores para URLs sin mapear
> > > > - Ejemplo de código sin lambdas
> > > >
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/neosoma/ventas-udemy-course/pull/1
> > > > Commit Summary
> > > >
> > > > - Add README.md file.
> > > > - Add an ErrorHandler to avoid Whitelabel error pages.
> > > > - Add API calls examples.
> > > > - Add an example of Java Vanilla code that does the same as lambdas.
> > > >
> > > > File Changes
> > > >
> > > > - *A* API_Calls.md
> > > > <
> > >
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-aba3c5b82dfdbeb1f04c965e4778df56d55dba5db572d34ecceb6e2a32768c6b
> > > >
> > > > (53)
> > > > - *A* README.md
> > > > <
> > >
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> > > >
> > > > (76)
> > > > - *M*
> src/main/java/com/ventas/ventas/controller/ClienteController.java
> > > > <
> > >
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-79b3cfaa310dda5366c476edd84e4557abc3cecfe24981936fe7372ac84b7f78
> > > >
> > > > (13)
> > > > - *A*
> > > >
> src/main/java/com/ventas/ventas/controller/ErrorHandlerController.java
> > > > <
> > >
> >
> https://github.com/neosoma/ventas-udemy-course/pull/1/files#diff-2ec20e5934d4d0949a45797b8794b9063b2983a783095c55d74d5bf0537de94b
> > > >
> > > > (24)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/neosoma/ventas-udemy-course/pull/1.patch
> > > > - https://github.com/neosoma/ventas-udemy-course/pull/1.diff
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/neosoma/ventas-udemy-course/pull/1>, or
> > unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/ [...]